{{- if .Values.contextBroker.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.contextBroker.generatePasswords.secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "nemobil.labels" . | nindent 4 }}
data:
  postgres-user-password: {{ randAlphaNum 30 | b64enc | quote }}
  postgres-admin-password: {{ randAlphaNum 30 | b64enc | quote }}
{{- end }}