{{- if .Values.contextFile.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-file
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: context-file
    {{ include "nemobil.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: context-file
  template:
    metadata:
      labels:
        app.kubernetes.io/name: context-file
    spec:
      containers:
        - name: context-file
          imagePullPolicy: Always
          image: "lipanski/docker-static-website:2.1.0"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: context-file
              mountPath: /home/static/context-file
      volumes:
        - name: context-file
          configMap:
            name: context-file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: context-file
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: context-file
    {{ include "nemobil.labels" . | nindent 4 }}
data:
  ngsild-context.jsonld: |-
    {{ .Values.contextFile.context | nindent 4 }}
  {{- with .Values.contextFile.model }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: context-file
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: context-file
    {{ include "nemobil.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 3000
      protocol: TCP
      name: "http"
  selector:
    app.kubernetes.io/name: context-file
{{- end }}