{{- if .Values.grafana.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.grafana.generatePasswords.secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "nemobil.labels" . | nindent 4 }}
data:
  admin-user: {{ default "admin" | b64enc | quote }}
  admin-password: {{ randAlphaNum 30 | b64enc | quote }}
{{- end }}