apiVersion: v2
name: nemobil
description: Umbrella Chart for the NeMo.Bil deployment, combining all essential parts of a deployment.
type: application
version: 1.0.0
dependencies:
  # monitoring
  - name: grafana
    alias: grafana
    condition: grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: 8.0.2
  # context-broker
  - name: scorpio-broker-aaio
    alias: scorpio
    condition: scorpio.enabled
    repository: https://fiware.github.io/helm-charts
    version: 0.4.7
  - name: postgresql
    alias: postgis
    condition: postgis.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
  # Mock Operational Planning
  - name: wiremock
    alias: reisewitz
    condition: reisewitz.enabled
    repository: https://pulledtim.github.io/helm-charts
    version: 1.1.2
  # Subscriptions
  - name: ngsild-subscriber
    alias: rw-request-subscription
    condition: rw-request-subscription.enabled
    repository: https://pulledtim.github.io/helm-charts
    version: 2.0.8
  - name: ngsild-subscriber
    alias: rw-trip-subscription
    condition: rw-trip-subscription.enabled
    repository: https://pulledtim.github.io/helm-charts
    version: 2.0.8